FROM node:18-alpine as build

WORKDIR /app

# Copiar arquivos de configuração primeiro
COPY package*.json ./
COPY vite.config.ts ./
COPY tailwind.config.js ./

# Instalar dependências
RUN npm install

# Copiar arquivos do projeto
COPY . .

# Gerar build
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 